apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cd-pipeline-run
spec:
  pipelineRef:
    name: cd-pipeline
  params:
    - name: repo-url
      value: https://github.com/ibm-developer-skills-network/wtecc-CICD_PracticeCode.git
    - name: branch
      value: main
    - name: app-name
      value: my-app
    - name: build-image
      value: image-registry.openshift-image-registry.svc:5000/sn-labs-u2023csvarun/my-app:latest
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc
